#theme = "slick"
#theme = "native"
theme= "nord-snow-storm"
icons = "awesome"

#[[block]]

#block = "pacman"
#interval = 1
#format = "{pacman} + {aur} = {both} updates available"
#format_singular = "{both} update available"
#format_up_to_date = "system up to date"
#critical_updates_regex = "(linux|linux-lts|linux-zen)"
# aur_command should output available updates to stdout (ie behave as echo -ne "update\n")
#aur_command = "yay -Qua"

#[[block]]
#block = "xrandr"
#icons = true
#resolution = true
#interval = 60

[[block]]
block = "net"
device = "enp0s25"
format = "{ssid} {signal_strength}"
interval = 5

#[[block]]
#block = "net"
#device = "enp0s25"
#format = "{ip}"
#interval = 5


[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 60
warning = 20.0
alert = 10.0
format = "{icon} {available} free"

[[block]]
block = "cpu"
interval = 5
[block.theme_overrides]
idle_bg = "#101010"
idle_fg = "#ffffff"



[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used}"
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95
[block.theme_overrides]
idle_bg = "#303030"
idle_fg = "#ffffff"

[[block]]
block = "sound"
#device = "hw0,1"
[block.theme_overrides]
idle_bg = "#101010"
idle_fg = "#ffffff"

[[block]]
block = "battery"
interval = 5
if_command = "test -e /sys/class/power_supply/BAT0"
format = "{percentage} {time} {power}"
[block.theme_overrides]
idle_bg = "#303030"
idle_fg = "#ffffff"

[[block]]
block = "time"
interval = 1
format = "%a %d/%m %T"
[block.theme_overrides]
idle_bg = "#101010"
idle_fg = "#ffffff"
